version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin